version: '3.9'
services:
  
  nginx:
    restart: always
    build:
      context: ./nginx
    networks:
      - tts
      - wav2lip
    depends_on:
      - tts
      - wav2lip
    ports:
      - 80:80
  tts:
    build:
      context: ./ai/tts
    networks:
      - tts
    volumes:
      - shared_data:/workspace/voice
  wav2lip:
    build:
      context: ./ai/wav2lip
    networks:
      - wav2lip
    volumes:
    - shared_data:/workspace/video
networks:
  tts:
  wav2lip:
volumes:
  shared_data:
