version: '3.9'
services:
  backend:
    build:
      context: ./backend
    networks:
      - private
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://ecs-newsvision.cadlryevxwwf.ap-northeast-2.rds.amazonaws.com/newsvision
      SPRING_DATASOURCE_USERNAME: jinseok
      SPRING_DATASOURCE_PASSWORD: liverpool12!    
  nginx:
    build:
      context: ./nginx
    networks:
      - public
      - private
      - tts
      - wav2lip
    ports:
      - 80:80
  frontend:
    build: 
      context: ./frontend/news-vision
      dockerfile: Dockerfile.prod
    networks:
      - public
    volumes:
      - shared_data:/app/video
    stdin_open: true
  tts:
    build:
      context: ./ai/tts
      dockerfile: Dockerfile.prod
    networks:
      - tts
    volumes:
      - shared_data:/workspace/voice
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
  wav2lip:
    build:
      context: ./ai/wav2lip
      dockerfile: Dockerfile.prod
    networks:
      - wav2lip
    volumes:
      - shared_data:/workspace/video
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
networks:
  public:
  private:
  wav2lip:
  tts:
volumes:
  shared_data:
