spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/newsVision
        username: root
        password:
#root 설정후 각자 username, password 넣기 ex) root dsfksadljfsadlfj!
    jpa:
        hibernate:
          ddl-auto: create
        show-sql: true


#하이버네이트에서 자동으로 생성

#    sql:
#        init:
#            mode: always
#            schema-locations: classpath:schema.sql
#            data-locations: